#!/usr/bin/env python
#coding=utf8

from vedur import Weather

v = Weather()

weather = [v.weather,
           (u"%s°C", v.temperature,),
           (u"%s m/s", v.wind,),
           v.winddirection]

def get_descr(param):
    if isinstance(param, (tuple, list,)):
        render_str = param[0]
        param = param[1]
    else:
        render_str = ""
    if param:
        if render_str:
            return render_str % param
        return param
    return ""

weather = map(lambda x: get_descr(x), weather)
print ", ".join(weather)
